Add support for meta command.
go-kiss/memcache pull request #2
Opened 2022-03-01 05:32 UTC by CDog34

2022-03-01 05:49 UTC, taoso commented on meta_test.go
> +		WithSize(),
需要检查返回值的 meta 信息

2022-03-04 01:48 UTC, taoso commented on meta_options.go
> +func CasToken(v int64) casToken {
所有的 cas 都应该从 memcached 获取，不存在用户事先知道 cas 的情景。所以不需要暴露`CasToken`函数。

2022-03-04 01:53 UTC, taoso commented on conn.go
> +func processMetaResponse(r *bufio.Reader) (isNoOp bool, mr MetaResult, err error) {
`process`改成`parse`？感觉`process`太宽泛了。

2022-03-04 01:54 UTC, taoso commented on conn.go
> +func parseMetaResponse(r *bufio.Reader) (mr MetaResult, err error) {
这里没有具体逻辑，要不要跟`processMetaResponse`合并

2022-03-04 02:04 UTC, taoso commented on conn.go
> +		statusLine := strings.Split(strings.Trim(string(statusLineRaw[len(resultHD):]), " "), " ")
可以尝试下面的写法，现有的嵌套有点多，看着眼花😵‍💫
```go
statusLine := strings.Fields(string(statusLineRaw))
mr, err = obtainMetaFlagsResults(statusLine[1:]) // skip HD
```

VA 部分也是类似。

2022-03-04 03:44 UTC, taoso commented on conn.go
> +		if mr.Value, err = ioutil.ReadAll(io.LimitReader(r, size+int64(len(crlf)))); err != nil {
这个地方用`io.Readfull`比较好，可以避免额外分配内存。ReadAll 适用于读取长度不确定的情况。

2022-03-04 03:47 UTC, taoso commented on meta_flags.go
> +func MetaFlag(name, input string, setFunc func(*MetaResult, string) error) metaFlager {
flag 相关的方法都不要暴露出去

2022-03-04 03:50 UTC, taoso commented on meta_options.go
> +	if mgo.BinaryKey {
Binary Key 需要 key 是 base64 编码。如果要对外提供 binary 支持，那应该在 sdk 中完成 base64 编码码和解码。这个处理起来有点复杂。

2022-03-04 04:21 UTC, taoso commented on meta_flags.go
> +		r := []rune(f)
为什么要转成`[]rune`?

2022-03-04 04:29 UTC, CDog34 commented on meta_flags.go
> +		r := []rune(f)
<img width="551" alt="image" src="https://user-images.githubusercontent.com/11211603/156699664-99b5c2fc-d44c-452e-bab8-e080d13342c3.png">

2022-03-04 04:42 UTC, CDog34 commented on meta_options.go
> +	if mgo.BinaryKey {
现有方法可以让外部做完 base64 编码再传字符串进来。
要么所有方法的 key 参数也改成 []byte，根据 WithBinary 决定是直接转成 string 存还是过一遍 base64 编码。

2022-03-04 06:48 UTC, taoso commented on meta_flags.go
> +		r := []rune(f)
问题是所有flag 都是英文单字母呀

2022-03-04 07:34 UTC, CDog34 commented on meta_flags.go
> +		r := []rune(f)
写这段代码的时候，我思考的问题是「从一个字符串中截取一个字符正确的方法是什么？」
对 string 取切片操作是按照字节取的，而单个 utf-8 字符可能不止一个字节，直接对字符串用切片取值显然不是上述问题的解。

当然这边目前的情况是 meta flag 都是 ascii 字符，都只占一个字节且位于字符串开头，简单用 string[0] 看起来可以解决问题。但本着不给将来挖坑的想法，我还是用了比较严谨的写法。如果有性能或其他方面的问题，也可以改成简单的写法。

2022-03-04 07:40 UTC, taoso commented on meta_flags.go
> +		r := []rune(f)
根据 memcached 的[协议](https://github.com/memcached/memcached/blob/master/doc/protocol.txt#L82):

> Meta commands are a set of new ASCII-based commands.

解析 flags 的时候无须考虑非 ASCII 字符的情形。即便是非 ASCII 编码，大多数也是兼容 ASCII 字符的。也就是说，对于各类 meat 指令和 flag 标记，在大多数编码中都是一样的，不存在截断问题。

防御式编码自然是好，但会带来额外的开销。如果只有开销而没有收益，则不足取。

2022-03-04 08:03 UTC, CDog34 commented on meta_flags.go
> +		r := []rune(f)
改成直接字符串切片取值了。

2022-03-04 15:09 UTC, taoso requested changes

2022-03-04 15:09 UTC, taoso commented on conn.go
> +	case "EN":
可以写成`case "EN", "NF":`

2022-03-04 15:09 UTC, taoso commented on conn.go
> +		size, err = strconv.ParseInt(status[0], 10, 64)
这里可以使用`strconv.Atoi`，返回的是`int`，后面跟`len`等函数配合的时候可以避免类型转换。

2022-03-04 15:09 UTC, taoso commented on conn.go
> +func parseMetaResponse(r *bufio.Reader) (isNoOp bool, mr MetaResult, err error) {
感觉没有地方在用这个 isNoOp

2022-03-04 15:09 UTC, taoso commented on meta.go
> +	IsSentWon  bool
在返回值中`W`和`Z`是互斥的吧。所有并发请求中，只有一个会拿到`W`，其他都是`Z`。所以收到`Z`后对应`IsWon`为`false`，不需要额外引入`IsSentWon`吧。

2022-03-04 15:09 UTC, taoso commented on meta_flags.go
> +var responseFlags = []metaFlager{
`responseFlags`跟`globalRegisteredFlags`的值是一样的，但为什么一个是 slice 另一个是 map？能不能合并？

2022-03-04 15:09 UTC, taoso commented on meta_options.go
> +	RequestRecacheWithTTL uint64 // if token is less than remaining TTL win for recache
要不就叫`RecacheWithTTL`？本身`MetaGetOptions`就是用于 request，不需要额外加前缀。

2022-03-04 15:09 UTC, taoso commented on conn.go
> +		_, err = io.ReadFull(r, mr.Value)
风格建议：

```go
if _, err = io.ReadFull(r, mr.Value); err != nil {
  return
}
```

2022-03-04 15:09 UTC, taoso commented on meta_flags.go
> +		if ff, ok := globalRegisteredFlags[k]; ok {
`globalRegisteredFlags`只有这一处使用，是不是可以直接改为 switch ?

2022-03-04 15:09 UTC, taoso commented on meta_flags.go
> +	mr.CasToken.setted = true
如果服务端没有返回 cas，为什么这里也得设为 setted?

2022-03-04 15:09 UTC, taoso commented on meta.go
> +func (c *Client) MetaGet(ctx context.Context, key []byte, opt MetaGetOptions) (i MetaResult, err error) {
关于 binary key 的问题，如果要支持，应该对外隐藏 base64 细节。也就是说，业务上应该可以随便传 key，根据 binary key 标记确定是否需要 base64。从这个角度上看，把 key 改成 []byte 非常合理。

但是，根据业务开发经验，我们在多数情况下还是以 string 作为 key。SDK 在底层也是使用 string 拼接的方式构建请求信息，而使用 binary key 又是一种相对小众的优化场景。基于以上三点，将 key 的类型从 string 改为 []byte 感觉成本就有点高了。这种设计会导致大量的 string -> []byte -> string 这样的类型转换。

所以，我建议保持原有的 string key 接口，在 XxxOptions 中引入 `BinaryKey []byte` 字段。如果`BinaryKey`不为空，则对其进行 base64 编码，用作 key 拼接 memcached 请求对象。

这样的设计优先保证 key 为 string 的大多数情景，同时开放了 binary key 这种特殊场景能力。

2022-03-04 15:09 UTC, taoso commented on meta_test.go
> +	k, err := os.ReadFile("binaryKey.png")
binary key 请使用转义字符构建。其实，binary key 的典型场景是用字符串表示数字的场景。

比如，某 ID 为`uint16`，最大为`65535`。如果用字符串表示，需要用五个字节。如果用binary表示，只需两个字节。

这里，并不是要用任意二进制内容当 key。

2022-03-04 15:09 UTC, taoso commented on meta_test.go
> +	k, err := os.ReadFile("binaryKey.png")
另外，不要提交`.DS_Store`这类无关文件。git add/commit/push 之前请务必检查改动内容是否符合预期。

2022-03-04 15:09 UTC, taoso commented on meta_options.go
> +	ReturnCasToken   bool // return item cas token
从语义上讲`ReturnXxx`非常合适。但考虑到 go 语言偏向比较短的名字。所以是不是可以将`ReturnXxx`统一换成`GetXxx`。这是纯粹是个人风格上的偏好建议，仅供参考。

2022-03-04 15:09 UTC, taoso commented on meta_options.go
> +	SetTTL         int64       // Time-To-Live for item, see "Expiration" above.
`SetXxx`是不是直接就可以叫`Xxx`呢？风格建议。

2022-03-04 15:09 UTC, taoso commented on meta.go
> +	Value      []byte
ma 指令如果需要返回 value 的话，那结果一定是整数。这类情况在业务代码里比较常见，要不要在设置了`v`标记后直接将结果解析成整数？

2022-03-04 15:09 UTC, taoso commented on meta_flags.go
> +		if ff, ok := globalRegisteredFlags[k]; ok {
换成 switch 之后，只需要根据各种 case 对 mr 相应的字段赋值，obtain 方法也不需要了。

2022-03-04 15:09 UTC, taoso commented on meta_flags.go
> +		v, err := strconv.ParseUint(d, 10, 32)
所有 obtain 函数解析的内容都是从服务端发出，理论上不会出现类型错误。比如，正常的服务端不会返回一个无法解析的字符表示的数字。但如果服务端或者中间代理有bug，则可能出现这类情况。为此，我建议引入一种特殊的错误叫 `ErrProtocol`。然后使用`fmt.Errorf("%s, %w", err, ErrProtocol)`包装，后面可以通过`errors.Is(err, ErrProtocol)`识别。

具体处理方式可以参见：https://go.dev/blog/go1.13-errors

2022-03-04 15:09 UTC, taoso commented on meta_flags.go
> +	token = strings.ReplaceAll(token, " ", "_")
Memcached 协议没有规定说自动将 opaque 中的空格转成下划线吧。如果有，请提供出处。如果没有，建议直接报错，让调用方处理。

2022-03-04 15:09 UTC, taoso commented on meta_test.go
> +	k, v, f, ttl, ttlDelta, wait, ctx, nv := []byte("KIANA"), []byte("KASLANA"), uint32(114514), int64(300), int64(20), int64(2), context.Background(), []byte("KALLEN")
一行不宜过长，也不宜在一行里写太多的变量赋值

2022-03-04 15:17 UTC, CDog34 commented on meta.go
> +	Value      []byte
可以提供一个 MetaResult.Int64() 方法把 value 转成 int64
同理也可提供一个 String 方法
好像也可以提供一个 JsonUnmarshal 方法

2022-03-04 15:19 UTC, taoso commented on conn.go
> +func parseMetaResponse(r *bufio.Reader) (isNoOp bool, mr MetaResult, err error) {
或者说，这里的`isNoOp`是不是可以放到`MetaResult`中，不需要单独返回？

2022-03-04 15:24 UTC, taoso commented on meta.go
> +	Value      []byte
提供工具函数自然不错，老的 Item 中也有类似的功能。但 ma 指令非常特别，它的返回值一定是整数。除非开发者没有传入`v`标记，不然，他一定会执行整数解析操作。至于 JsonUnmarshal 这类方法，因为不确定业务代码使用的频率，可以先不提供。

2022-03-04 15:26 UTC, CDog34 commented on meta.go
> +	IsSentWon  bool
仅用一个变量 IsWon 时，当 IsWon 为 false 时，无法表示是因为没有发起更新请求还是已经有先驱请求赢得更新。
虽然业务可能并不关心没有赢得更新时具体是为何没有赢得更新的，但是既然 memcache 提供了 Z 这个 flag ，而不是直接省略 W，说明在某些情况下这个信息可能还是有用的，我认为作为基础库不应该屏蔽这个细节。

2022-03-04 15:31 UTC, CDog34 commented on conn.go
> +func parseMetaResponse(r *bufio.Reader) (isNoOp bool, mr MetaResult, err error) {
isNoOp 是之前在解析多个串行请求时用到的。
解析多个请求时外部会加一个死循环，通过 isNoOp 判断是否需要跳出循环。

暂时没有想到在这个方法内部不暴露 isNoOp 的情况下，既处理单个结果又能处理多个结果的方式。（要不然就多加一个传入参数 isMulti，但个人感觉意义不大）

2022-03-04 15:36 UTC, CDog34 commented on meta.go
> +	Value      []byte
那 MetaResult 里再加一个 IntValue int64 字段？我觉得有点丑。

2022-03-04 15:42 UTC, taoso commented on meta.go
> +	IsSentWon  bool
这里面有四种情况。
- 第一种，用户根本没有请求并发更新锁，也自然不会检查 IsWon 的取值。而这个时候 IsWon 取默认值，为 false，也不会产生任何影响。
- 第二种，如果用户是想获取并发更新锁，但忘记设置相应的标记，那 IsWon 取默认值为 false。这等价于没有拿到锁，所以放弃更新。这也符合直觉。SDK应该避免在没有拿到锁的情况下去更新。
- 第三种，用户主动请求并发更新锁并且胜出，此时 IsWon 为 true，没有任何争议。
- 第四种，用户主动请求并发更新锁但没有胜出，这个时候最核心的事实是用户没有权利去更新缓存。而这个事实是通过`Z`标记来表达的。如果 Memcached 的协议没有规定`Z`标记，而是只给胜出的用户返回`W`标记，也可以达到同样的效果。这时，并没有损失什么信息。

你指出只用`IsWon`一个字段无法区分第四种情况和第一种情况。其实，这种区分已经**隐含在用户的行为中**。同样是`IsWon`为 false，第一种情况用户不会检查 IsWon，而第四种会检查。

对于需要获取并发锁的场景，只要检查`IsWon`是否为true就已经足够了，不需要再检查`IsSentWon`。基于此，我认为不必再对外暴露`IsSentWon`字段。

2022-03-04 15:44 UTC, taoso commented on conn.go
> +func parseMetaResponse(r *bufio.Reader) (isNoOp bool, mr MetaResult, err error) {
因为现在都是这样调用的：

```go
_, mr, err = parseMetaResponse(c.rw.Reader)
```

所以我建议将`isNoOp`移到`MetaResult`中，且不对外暴露。

2022-03-04 15:47 UTC, CDog34 commented on meta_flags.go
> +var responseFlags = []metaFlager{
我的想法是把每个 flag 的字母标记，拼装逻辑和结果解析的逻辑收敛到一起，也就是 metaFlager 接口。
原先想的是在解析 response 的时候遍历传入的 []metaFlager 生成一个map<key, metaFlager> 来生成 MetaResult，后来觉得每次都要遍历 []metaFlager 性能太差，就想着事先生成好全局的 map<key, metaFlager> 解析时直接用。
又因为 key 是 metaFlager 的一个内部属性，如果直接定义成  map<key, metaFlager> 会重复写一遍 key，本着*不要重复你自己*的原则，就先用了一个 slice 把 metaFlager 列出来，再在 init 函数里遍历成 map。

2022-03-04 15:49 UTC, CDog34 commented on meta_flags.go
> +		if ff, ok := globalRegisteredFlags[k]; ok {
这里这么写本质上我还是想把每个 flag 的字母标记，拼装逻辑和结果解析的逻辑内聚到一起。

2022-03-04 15:51 UTC, taoso commented on meta.go
> +	Value      []byte
确实有点丑。因为 ma 的结果必然是整数，所以我们可以在解析服务器响应的时候顺手解析整数结果。这样一样，解析整数过程中的报错可以跟其他协议错误合并处理。

如果换成提供 Int64() 函数，那么在使用的时候就需要再一次处理解析整数的报错。这也有点丑。

2022-03-04 15:58 UTC, taoso commented on meta_flags.go
> +var responseFlags = []metaFlager{
现在的这种写法已经增加了阅读和理解的难度。如果没有实际的收益，还是想办法调整。

> 如果直接定义成 map<key, metaFlager> 会重复写一遍 key，本着不要重复你自己的原则，就先用了一个 slice 把 metaFlager 列出来，再在 init 函数里遍历成 map

我非常赞同「不要重复你自己的原则」。但是，不重复的前提需要兼顾性能和可读性。这里把 slice 统一转换成 map 自然是没有问题。但是每次从 map 中取对应的 flag 却不是没有成本的。做为基础的协议解析逻辑，我们明确所有可能的 flag 的前提下还要动态地去查询 map，这里会涉及到不必要的哈希开销。我认为不足取。

对于这种在协议层就非常明确的事情，应该使用 switch 明确写出各个分支。你可以看看诸如 nginx 的 http 协议解析部分，都是这样处理的。动态查 map 不但有性能开销，还会增加阅读理解难度。

2022-03-04 16:01 UTC, taoso commented on meta_flags.go
> +		if ff, ok := globalRegisteredFlags[k]; ok {
从现的代码来看，拼装逻辑和结果解析逻辑不尽相同。放到一起不但导致阅读成本增加，还带来了额外的运行时查询 map 开销（前面已经讲过了）。所以放到一起的好处是什么呢？

2022-03-07 09:18 UTC, taoso commented on meta.go
> +	if len(key) == 0 {
这个要检查吗？如果要检查，是不是也要检查一下最大长度？还有 binary key 的情况。

2022-03-07 09:19 UTC, CDog34 commented on meta.go
> +	if len(key) == 0 {
最大长度在 conn 的方法里会检查

2022-03-07 09:22 UTC, taoso commented on meta.go
> +	if len(key) == 0 {
那是不是在`legalKey`统一检查一下就好了？

2022-03-07 09:23 UTC, CDog34 commented on meta_options.go
> +	SetTTL         int64       // Time-To-Live for item, see "Expiration" above.
建议保留 Set 前缀。
mg 命令可以通过 T 改变 TTL，形如 `MetaGet(ctx,MetaGetOptions{..., TTL: xxx,})` 有歧义。

2022-03-07 09:24 UTC, taoso commented on meta_options.go
> +	SetTTL         int64       // Time-To-Live for item, see "Expiration" above.
有道理

2022-03-07 10:21 UTC, taoso commented on conn.go
>  func (c *Conn) MetaGet(key string, flags []metaFlag) (mr MetaResult, err error) {
Conn 级别能否提供一个通用的 Meta 方法？我看目前的 MetaXxx 都非常相似

2022-03-07 13:45 UTC, taoso commented on conn.go
>  func (c *Conn) MetaArithmetic(key string, flags []metaFlag) (mr MetaResult, err error) {
是不是可以直接在 Client 中调 metaCmd 方法？感觉 Conn 中的 MetaXxx 好像没有实质内容

2022-03-08 03:14 UTC, merged